---
- name: "apt | ensure Google linux signing key present"
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  become: yes

- name: "apt | ensure previous repository for Google Chrome is absent, as Google removed the x86 distribution"
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: absent
  become: yes

- name: "apt | ensure Google chrome repo present, using a workaround for missing x86 distribution"
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"
  register: google_repo
  become: yes

- name: "apt | update cache"
  apt: update_cache=yes
  when: google_repo.changed
  become: yes
  
- name: "apt | ensure Google chrome present"
  apt: 
    name: "google-chrome-stable"
    update_cache: yes
  become: yes

- name: "apt | ensure Google hangouts present"
  apt: 
    name: "google-chrome-stable"
    update_cache: yes
  become: yes
